<a href="https://colab.research.google.com/github/sanyamsh7/Notebooks/blob/main/Exercises03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


df = pd.DataFrame({'years': [1, 2, 3, 4, 5, 6],
                   'salary': [4000, 4250, 4500, 4750, 5000, 5250]})

**Normal Equation is an analytical approach to Linear Regression with a Least Square Cost Function.
We can directly find out the value of θ without using Gradient Descent. Following this 
approach is an effective and time-saving option when are working with a dataset with small features**

In [4]:
m = len(df)
m

6

In [5]:
X1 = df['years'].values
X1

array([1, 2, 3, 4, 5, 6])

In [7]:
Y = df['salary'].values
Y

array([4000, 4250, 4500, 4750, 5000, 5250])

In [8]:
X1.reshape(m, 1)    # changed X1 to a column

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
X1 = X1.reshape(m, 1)

In [12]:
bias = np.ones((m, 1))    # 6x1

In [15]:
#np.append - used to merge two arrays and original remains same
np.append(bias, X1, axis = 1)

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [16]:
X = np.append(bias, X1, axis = 1)

image.png

In [18]:
np.linalg.inv(np.dot(X.T, X))    # first inverse dot product

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [20]:
 np.dot(X.T, Y)     # second dot product in the equation

array([ 27750., 101500.])

In [23]:
coefs  = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))
coefs

array([3750.,  250.])

In [25]:
print(f'Linear regression: {coefs[0]:.2f} + {coefs[1]:.2f}x')


Linear regression: 3750.00 + 250.00x


In [32]:
# NOW USING SCIKIT LEARN 
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression


df = pd.DataFrame({'years': [1, 2, 3, 4, 5, 6],
                   'salary': [4000, 4250, 4500, 4750, 5000, 5250]})

lr  = LinearRegression()
lr.fit(df[['years']], df[['salary']])
print("Linear regression: {} + {}x".format(lr.intercept_[0], lr.coef_[0][0]))

Linear regression: 3750.0 + 250.0x
